name: Issue-PR Linking Validation

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, converted_to_draft, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created, edited]

jobs:
  validate-issue-pr-linking:
    runs-on: ubuntu-latest
    name: Validate Issue-PR Linking Compliance
    
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Validate Issue-PR Linking
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          
          // Helper function to extract issue number from branch name
          function extractIssueNumber(branchName) {
            const match = branchName.match(/^(?:feature|bugfix|hotfix)\/issue-(\d+)-/);
            return match ? parseInt(match[1]) : null;
          }
          
          // Helper function to check if issue has PR link
          async function issueHasPRLink(issueNumber, prNumber) {
            try {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              
              const prLinkPattern = new RegExp(`(pull/${prNumber}|PR #${prNumber}|#${prNumber})`, 'i');
              
              return comments.data.some(comment => 
                prLinkPattern.test(comment.body)
              );
            } catch (error) {
              console.log(`Error checking issue comments: ${error.message}`);
              return false;
            }
          }
          
          // Helper function to add reminder comment to PR
          async function addPRReminder(prNumber, issueNumber) {
            const reminderMessage = `
          ## 📝 Issue Linking Reminder
          
          This PR appears to be related to issue #${issueNumber}, but the issue doesn't have a link to this PR yet.
          
          **According to MANDATORY-RULES.md, you should:**
          - Comment on issue #${issueNumber} with a link to this PR
          
          **Quick fix:**
          \`\`\`bash
          gh issue comment ${issueNumber} --body "Created PR #${prNumber}: ${context.payload.pull_request.html_url}"
          \`\`\`
          
          This comment will be automatically removed once the issue is properly linked.
          
          *This is an automated reminder to help maintain project documentation standards.*
            `;
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: reminderMessage
              });
            } catch (error) {
              console.log(`Error adding reminder comment: ${error.message}`);
            }
          }
          
          // Helper function to remove existing reminder comments
          async function removeExistingReminders(prNumber) {
            try {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });
              
              const reminderComments = comments.data.filter(comment => 
                comment.body.includes('📝 Issue Linking Reminder') &&
                comment.user.type === 'Bot'
              );
              
              for (const comment of reminderComments) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                });
              }
            } catch (error) {
              console.log(`Error removing reminder comments: ${error.message}`);
            }
          }
          
          // Helper function to remind about review feedback
          async function addReviewFeedbackReminder(prNumber, issueNumber, reviewState) {
            if (reviewState !== 'changes_requested') return;
            
            const reminderMessage = `
          ## 🔍 Review Feedback Update Reminder
          
          This PR has received a review requesting changes. According to MANDATORY-RULES.md, you should:
          - Update issue #${issueNumber} with the review feedback received
          - Document any changes or decisions made in response
          
          **Quick update:**
          \`\`\`bash
          gh issue comment ${issueNumber} --body "PR #${prNumber} received review feedback. Working on requested changes..."
          \`\`\`
          
          *This reminder helps maintain project context and communication.*
            `;
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: reminderMessage
              });
            } catch (error) {
              console.log(`Error adding review reminder: ${error.message}`);
            }
          }
          
          // Helper function to auto-comment on issue when PR is created
          async function notifyIssueOfPR(issueNumber, prNumber, prData) {
            const message = `## 🔗 Pull Request Created
          
          PR #${prNumber} has been created to address this issue.
          
          **PR Details:**
          - Title: ${prData.title}
          - Branch: \`${prData.head.ref}\`
          - Status: ${prData.draft ? '📝 Draft' : '✅ Ready for review'}
          - Link: ${prData.html_url}
          
          **Next Steps:**
          1. Monitor PR progress
          2. Update this issue with implementation decisions
          3. Document any changes from the original plan
          
          *This is an automated notification to maintain issue context.*`;
            
            try {
              // Check if we already notified
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              
              const alreadyNotified = comments.data.some(comment => 
                comment.body.includes('🔗 Pull Request Created') &&
                comment.body.includes(`PR #${prNumber}`) &&
                comment.user.type === 'Bot'
              );
              
              if (!alreadyNotified) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: message
                });
                console.log(`✅ Notified issue #${issueNumber} about PR #${prNumber}`);
              }
            } catch (error) {
              console.log(`Error notifying issue: ${error.message}`);
            }
          }
          
          // Helper function to notify issue when PR is closed
          async function notifyIssueOfPRClosure(issueNumber, prNumber, prData, merged) {
            const message = merged
              ? `## ✅ Pull Request Merged
          
          PR #${prNumber} has been successfully merged!
          
          **Merge Details:**
          - Merged by: @${prData.merged_by?.login || 'unknown'}
          - Merged at: ${new Date(prData.merged_at).toLocaleString()}
          - Commits: ${prData.commits}
          - Changes: +${prData.additions} -${prData.deletions}
          
          **Resolution:**
          This issue has been resolved by the merged PR. Please verify the implementation meets all requirements.
          
          *This is an automated notification. Consider closing this issue if fully resolved.*`
              : `## 🚫 Pull Request Closed
          
          PR #${prNumber} has been closed without merging.
          
          **Closure Details:**
          - Closed by: @${prData.closed_by?.login || 'unknown'}
          - Reason: ${prData.title.includes('[WIP]') ? 'Work in progress' : 'Not specified'}
          
          **Next Steps:**
          - Review why the PR was closed
          - Determine if this issue still needs to be addressed
          - Create a new PR if necessary
          
          *This is an automated notification to maintain issue context.*`;
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: message
              });
              console.log(`✅ Notified issue #${issueNumber} about PR #${prNumber} closure`);
            } catch (error) {
              console.log(`Error notifying issue of closure: ${error.message}`);
            }
          }
          
          // Main validation logic
          async function validateLinking() {
            if (context.eventName === 'pull_request') {
              const pr = context.payload.pull_request;
              const branchName = pr.head.ref;
              const issueNumber = extractIssueNumber(branchName);
              
              console.log(`PR #${pr.number}: ${pr.title}`);
              console.log(`Branch: ${branchName}`);
              console.log(`Extracted issue number: ${issueNumber}`);
              
              if (!issueNumber) {
                console.log('Branch does not follow issue convention - skipping validation');
                return;
              }
              
              // Check if issue exists
              try {
                await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber
                });
              } catch (error) {
                console.log(`Issue #${issueNumber} not found - skipping validation`);
                return;
              }
              
              // Handle different PR events
              if (context.payload.action === 'opened') {
                // Auto-notify issue when PR is created
                await notifyIssueOfPR(issueNumber, pr.number, pr);
              }
              
              if (context.payload.action === 'closed') {
                // Notify issue when PR is closed/merged
                await notifyIssueOfPRClosure(issueNumber, pr.number, pr, pr.merged);
                return; // No need for linking reminders on closed PRs
              }
              
              // Check if issue has PR link
              const hasLink = await issueHasPRLink(issueNumber, pr.number);
              
              if (!hasLink) {
                console.log(`Issue #${issueNumber} missing PR link - adding reminder`);
                await addPRReminder(pr.number, issueNumber);
              } else {
                console.log(`Issue #${issueNumber} has PR link - removing any existing reminders`);
                await removeExistingReminders(pr.number);
              }
              
            } else if (context.eventName === 'issue_comment') {
              // Check if a comment was added that might link to a PR
              const comment = context.payload.comment;
              const issueNumber = context.payload.issue.number;
              
              // Look for PR references in the comment
              const prReferencePattern = /(?:pull\/(\d+)|PR #(\d+)|#(\d+))/gi;
              let match;
              const referencedPRs = [];
              
              while ((match = prReferencePattern.exec(comment.body)) !== null) {
                const prNumber = match[1] || match[2] || match[3];
                if (prNumber) {
                  referencedPRs.push(parseInt(prNumber));
                }
              }
              
              // For each referenced PR, remove reminder comments
              for (const prNumber of referencedPRs) {
                try {
                  // Check if this PR exists and is related to this issue
                  const pr = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber
                  });
                  
                  const branchIssueNumber = extractIssueNumber(pr.data.head.ref);
                  
                  if (branchIssueNumber === issueNumber) {
                    console.log(`Removing reminders from PR #${prNumber} due to issue link`);
                    await removeExistingReminders(prNumber);
                  }
                } catch (error) {
                  console.log(`PR #${prNumber} not found or accessible`);
                }
              }
            }
          } else if (context.eventName === 'pull_request_review') {
            // Handle review events
            const review = context.payload.review;
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;
            const issueNumber = extractIssueNumber(branchName);
            
            console.log(`Review on PR #${pr.number}: ${review.state}`);
            
            if (!issueNumber) {
              console.log('Branch does not follow issue convention - skipping validation');
              return;
            }
            
            // Add reminder to update issue with review feedback
            await addReviewFeedbackReminder(pr.number, issueNumber, review.state);
          }
          }
          
          await validateLinking();

    - name: Add status check
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          
          // This is a non-blocking check - we always pass
          // The validation above provides reminders but doesn't block
          console.log('Issue-PR linking validation completed');
          console.log('This check provides reminders but does not block PRs');
          
          // Set a success status
          process.exit(0);